<?PHP
$CONN = NEW MYSQLI("LOCALHOST", "ROOT", "", "SQLI_LAB");

IF ($_POST) {
  $USER = $_POST['USERNAME'];
  $STMT = $CONN->PREPARE("SELECT * FROM USERS WHERE USERNAME=?");
  $STMT->BIND_PARAM("S", $USER);
  $STMT->EXECUTE();
  $RESULT = $STMT->GET_RESULT();

  ECHO ($RESULT->NUM_ROWS > 0) ? "LOGIN SUCCESSFUL" : "LOGIN FAILED";
}
?>

<FORM METHOD="POST">
  <INPUT NAME="USERNAME">
  <BUTTON TYPE="SUBMIT">LOGIN</BUTTON>
</FORM>
